apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-java
  namespace: community-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-java
  template:
    metadata:
      labels:
        app: postgres-java
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: communityalertsdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: community-alerts-secrets
                  key: java-db-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-java-pvc
