apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
  namespace: community-alerts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: communityalertsacr.azurecr.io/community-alerts/java-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: community-alerts-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-java:5432/communityalertsdb"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: community-alerts-secrets
                  key: java-db-password
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: community-alerts-secrets
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /api/v1/suburbs
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
