apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-notifications-pvc
  namespace: community-alerts
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
